/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardCampain: typeof import('./src/components/card/CardCampain.vue')['default']
    CardSuggestion: typeof import('./src/components/suggestion_box/CardSuggestion.vue')['default']
    Charts: typeof import('./src/components/exam/Charts.vue')['default']
    DocumentView: typeof import('./src/components/suggestion_box/DocumentView.vue')['default']
    Form: typeof import('./src/components/suggestion_box/Form.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Index: typeof import('./src/components/exam/Index.vue')['default']
    Login: typeof import('./src/components/user/Login.vue')['default']
    Notification: typeof import('./src/components/exam/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/suggestion_box/Test.vue')['default']
  }
}
